# docker compose for development

version: '3.8'

services:
  postgres:
    image: postgres:16.0
    environment:
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'

volumes:
  postgres:
